Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -42,8 +42,18 @@ jobs:
         port: ${{ secrets.SERVER_PORT }}
         script: |
           sudo apt-get update
-          cd /home/node-apps/MyCV/
+          if [ ! -d "/home/node-apps/MyCV/" ]; then
+            mkdir -p /home/node-apps/MyCV/
+            cd /home/node-apps/MyCV/
+            git init
+          else
+            cd /home/node-apps/MyCV/
+          fi
           git fetch origin main
           git reset --hard origin/main
+          if [ ! -f "package.json" ]; then
+            echo "package.json not found!"
+            exit 1
+          fi
           npm ci
           npm run build
